### ISSUE TITLE
Figure out what to do with the Exports view

### ISSUE THREAD

**Issue by aminomancer** [mozilla/bugzy#210]
Are we planning to use the [Exports view](https://www.bugzy.org/exports) for anything? The last export was some years ago and it looks like it's set up to catch exports from the [activity-stream repo](https://github.com/mozilla/activity-stream) (which is now archived) to mozilla-central. We could keep it around for reference, but would still be nice to get rid of the "consider exporting soon" warning.

**Comment by Mardak** [comment]
We can remove it. Someone can follow the export chain from https://bugzilla.mozilla.org/showdependencytree.cgi?id=1601754&hide_resolved=0 if desired
