### ISSUE TITLE
Show prioritized bugs to take on

### ISSUE THREAD

**Issue by Mardak** [mozilla/bugzy#219]
Maybe something like this query looking for unassigned P1/P2s:
https://bugzilla.mozilla.org/buglist.cgi?cmdtype=dorem&remaction=run&namedcmd=Messaging%20System%20Unassigned%20P1%2FP2&sharer_id=125983

It should probably be sorted by priority (P1 before P2) then iteration (current iteration then later then no iteration) then last updated. Unclear if we want to limit it to the first say 50 bugs vs all (currently 99).

This could probably be a separate view listed in the top left maybe just under Current Iteration?

cc @punamdahiya

**Comment by aminomancer** [comment]
Any ideas for the label? We're effectively limited to about 20 latin characters before it overflows.

**Comment by punamdahiya** [comment]
How about label as 'Next Release' as majority of the bugs should be P2
