### ISSUE TITLE
Turn icons in priority column into buttons that open the priority guide

### ISSUE THREAD

**Issue by rjfc** [mozilla/bugzy#255]
The icons in the priority column of the bug list are currently plain text. They should be turned into buttons that open the Priority Guide on the right. The arrow button in the priority guide should also have a `cursor: pointer` and a hover state.

The `--` should also be horizontally aligned with the rest of the priority icons in the column:
![image](https://user-images.githubusercontent.com/17807246/228053737-60aeb172-cbd0-475f-92ae-a24befaa1e85.png)

**Comment by aminomancer** [comment]
while you're at it, the priority guide's collapsed/expanded state is not stored anywhere, so it resets on every https load. you could make it a pref in localStorage. though maybe you know a better way
